require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Lint/UselessMethodDefinition: # This raises with useful method definitions (e.g. when the signature changes in an overriden method)
  Enabled: false

Metrics/AbcSize:
  Max: 55

Metrics/BlockLength:
  Max: 20
  AllowedMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 10

RSpec/ExampleLength:
  Max: 7

RSpec/MultipleExpectations:
  Max: 5
